{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 42,
   "metadata": {},
   "outputs": [],
   "source": [
    "import matplotlib.pyplot as plt\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from sklearn.model_selection import GridSearchCV,KFold\n",
    "import tensorflow as tf \n",
    "from tensorflow import keras \n",
    "from tensorflow.keras.models import Sequential\n",
    "from tensorflow.keras.layers import Dense \n",
    "from scikeras.wrappers import KerasClassifier\n",
    "from sklearn.preprocessing import LabelEncoder\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 43,
   "metadata": {},
   "outputs": [],
   "source": [
    "df_train = pd.read_csv('../../../datasets/parte2/treino/dataset_prepared.csv', na_filter= False)\n",
    "df_test = pd.read_csv('../../../datasets/parte2/teste/dataset_prepared.csv')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 44,
   "metadata": {},
   "outputs": [],
   "source": [
    "lb_make = LabelEncoder()\n",
    "df_train['injection_encoded'] = lb_make.fit_transform(df_train['injection'])\n",
    "df_train.drop('injection',inplace= True,axis=1)\n",
    "\n",
    "X = df_train.drop('injection_encoded', axis=1)\n",
    "y = df_train['injection_encoded']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 45,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: tensorflow in /Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages (2.11.0)\n",
      "Requirement already satisfied: absl-py>=1.0.0 in /Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages (from tensorflow) (1.4.0)\n",
      "Requirement already satisfied: astunparse>=1.6.0 in /Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages (from tensorflow) (1.6.3)\n",
      "Requirement already satisfied: flatbuffers>=2.0 in /Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages (from tensorflow) (2.0)\n",
      "Requirement already satisfied: gast<=0.4.0,>=0.2.1 in /Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages (from tensorflow) (0.4.0)\n",
      "Requirement already satisfied: google-pasta>=0.1.1 in /Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages (from tensorflow) (0.2.0)\n",
      "Requirement already satisfied: h5py>=2.9.0 in /Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages (from tensorflow) (3.9.0)\n",
      "Requirement already satisfied: libclang>=13.0.0 in /Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages (from tensorflow) (16.0.6)\n",
      "Requirement already satisfied: numpy>=1.20 in /Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages (from tensorflow) (1.26.2)\n",
      "Requirement already satisfied: opt-einsum>=2.3.2 in /Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages (from tensorflow) (3.3.0)\n",
      "Requirement already satisfied: packaging in /Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages (from tensorflow) (23.1)\n",
      "Requirement already satisfied: protobuf<3.20,>=3.9.2 in /Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages (from tensorflow) (3.19.6)\n",
      "Requirement already satisfied: setuptools in /Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages (from tensorflow) (68.2.2)\n",
      "Requirement already satisfied: six>=1.12.0 in /Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages (from tensorflow) (1.16.0)\n",
      "Requirement already satisfied: termcolor>=1.1.0 in /Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages (from tensorflow) (2.1.0)\n",
      "Requirement already satisfied: typing-extensions>=3.6.6 in /Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages (from tensorflow) (4.7.1)\n",
      "Requirement already satisfied: wrapt>=1.11.0 in /Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages (from tensorflow) (1.14.1)\n",
      "Requirement already satisfied: grpcio<2.0,>=1.24.3 in /Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages (from tensorflow) (1.42.0)\n",
      "Requirement already satisfied: tensorboard<2.12,>=2.11 in /Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages (from tensorflow) (2.11.0)\n",
      "Requirement already satisfied: tensorflow-estimator<2.12,>=2.11.0 in /Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages (from tensorflow) (2.11.0)\n",
      "Requirement already satisfied: keras<2.12,>=2.11.0 in /Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages (from tensorflow) (2.11.0)\n",
      "Requirement already satisfied: wheel<1.0,>=0.23.0 in /Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages (from astunparse>=1.6.0->tensorflow) (0.35.1)\n",
      "Requirement already satisfied: google-auth<3,>=1.6.3 in /Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages (from tensorboard<2.12,>=2.11->tensorflow) (2.22.0)\n",
      "Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages (from tensorboard<2.12,>=2.11->tensorflow) (0.4.4)\n",
      "Requirement already satisfied: markdown>=2.6.8 in /Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages (from tensorboard<2.12,>=2.11->tensorflow) (3.4.1)\n",
      "Requirement already satisfied: requests<3,>=2.21.0 in /Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages (from tensorboard<2.12,>=2.11->tensorflow) (2.31.0)\n",
      "Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in /Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages (from tensorboard<2.12,>=2.11->tensorflow) (0.6.1)\n",
      "Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages (from tensorboard<2.12,>=2.11->tensorflow) (1.8.1)\n",
      "Requirement already satisfied: werkzeug>=1.0.1 in /Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages (from tensorboard<2.12,>=2.11->tensorflow) (2.2.3)\n",
      "Requirement already satisfied: cachetools<6.0,>=2.0.0 in /Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.12,>=2.11->tensorflow) (4.2.2)\n",
      "Requirement already satisfied: pyasn1-modules>=0.2.1 in /Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.12,>=2.11->tensorflow) (0.2.8)\n",
      "Requirement already satisfied: rsa<5,>=3.1.4 in /Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.12,>=2.11->tensorflow) (4.7.2)\n",
      "Requirement already satisfied: urllib3<2.0 in /Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages (from google-auth<3,>=1.6.3->tensorboard<2.12,>=2.11->tensorflow) (1.26.18)\n",
      "Requirement already satisfied: requests-oauthlib>=0.7.0 in /Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.12,>=2.11->tensorflow) (1.3.0)\n",
      "Requirement already satisfied: charset-normalizer<4,>=2 in /Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorboard<2.12,>=2.11->tensorflow) (2.0.4)\n",
      "Requirement already satisfied: idna<4,>=2.5 in /Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorboard<2.12,>=2.11->tensorflow) (3.4)\n",
      "Requirement already satisfied: certifi>=2017.4.17 in /Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages (from requests<3,>=2.21.0->tensorboard<2.12,>=2.11->tensorflow) (2023.11.17)\n",
      "Requirement already satisfied: MarkupSafe>=2.1.1 in /Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages (from werkzeug>=1.0.1->tensorboard<2.12,>=2.11->tensorflow) (2.1.1)\n",
      "Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.12,>=2.11->tensorflow) (0.4.8)\n",
      "Requirement already satisfied: oauthlib>=3.0.0 in /Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.12,>=2.11->tensorflow) (3.2.2)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "%pip install tensorflow"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 46,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Usage:   \n",
      "  /Users/goncalobraga/miniconda3/envs/DAA/bin/python -m pip install [options] <requirement specifier> [package-index-options] ...\n",
      "  /Users/goncalobraga/miniconda3/envs/DAA/bin/python -m pip install [options] -r <requirements file> [package-index-options] ...\n",
      "  /Users/goncalobraga/miniconda3/envs/DAA/bin/python -m pip install [options] [-e] <vcs project url> ...\n",
      "  /Users/goncalobraga/miniconda3/envs/DAA/bin/python -m pip install [options] [-e] <local project path> ...\n",
      "  /Users/goncalobraga/miniconda3/envs/DAA/bin/python -m pip install [options] <archive url/path> ...\n",
      "\n",
      "no such option: -u\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "%pip install -upgrade keras"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 47,
   "metadata": {},
   "outputs": [],
   "source": [
    " # %pip install scikeras[tensorflow]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 48,
   "metadata": {},
   "outputs": [],
   "source": [
    "def build_model(activation = 'relu',learning_rate =0.01):\n",
    "    model = Sequential()\n",
    "    model.add(Dense(16,input_dim=21, activation = activation ))\n",
    "    model.add(Dense(8,activation=activation))\n",
    "    model.add(Dense(1,activation=activation)) # output \n",
    "    #Compile the model\n",
    "    model.compile(\n",
    "    loss = tf.keras.losses.SparseCategoricalCrossentropy(),\n",
    "    optimizer = tf.optimizers.Adam(learning_rate),\n",
    "    metrics = ['accuracy'])\n",
    "    return model "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 49,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Model: \"sequential_14\"\n",
      "_________________________________________________________________\n",
      " Layer (type)                Output Shape              Param #   \n",
      "=================================================================\n",
      " dense_42 (Dense)            (None, 16)                352       \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "                                                                 \n",
      " dense_43 (Dense)            (None, 8)                 136       \n",
      "                                                                 \n",
      " dense_44 (Dense)            (None, 1)                 9         \n",
      "                                                                 \n",
      "=================================================================\n",
      "Total params: 497\n",
      "Trainable params: 497\n",
      "Non-trainable params: 0\n",
      "_________________________________________________________________\n"
     ]
    }
   ],
   "source": [
    "model = build_model()\n",
    "model.summary()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 50,
   "metadata": {},
   "outputs": [],
   "source": [
    "optimizer = ['Adam', 'SGD','RMSProp']\n",
    "param_grid = dict(optimizer=optimizer)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 51,
   "metadata": {},
   "outputs": [],
   "source": [
    "kf = KFold(n_splits=2, shuffle=True, random_state=2023)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 52,
   "metadata": {},
   "outputs": [],
   "source": [
    "model = KerasClassifier(build_fn=build_model, epochs=1, batch_size=32, verbose=0)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 53,
   "metadata": {},
   "outputs": [],
   "source": [
    "grid_search = GridSearchCV(estimator = model, param_grid= param_grid, cv = kf, refit='True',verbose = 1 )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 54,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "        temp  feels_like  temp_min  temp_max  pressure  humidity  wind_speed  \\\n",
      "0      13.97       13.54     11.45     14.04      1027        81        1.96   \n",
      "1      13.48       13.02     13.43     13.90      1028        82        1.83   \n",
      "2      12.93       12.47     12.72     13.43      1027        84        1.96   \n",
      "3      12.61       12.15     10.34     12.93      1027        85        1.85   \n",
      "4      12.61       12.17      9.79     12.93      1027        86        1.83   \n",
      "...      ...         ...       ...       ...       ...       ...         ...   \n",
      "11011  15.70       15.57     15.57     15.72      1018        86        5.56   \n",
      "11012  15.55       15.43     12.72     15.70      1018        87        4.47   \n",
      "11013  13.45       13.28     12.23     13.99      1019        93        3.29   \n",
      "11014  12.93       12.73     12.23     13.43      1019        94        1.49   \n",
      "11015  12.93       12.76     12.23     13.43      1019        95        1.93   \n",
      "\n",
      "       clouds_all  hour  normal  ...  self-consumption  month  broken clouds  \\\n",
      "0              87     0   0.000  ...               0.0      9              0   \n",
      "1              91     1   0.000  ...               0.0      9              0   \n",
      "2              93     2   0.000  ...               0.0      9              0   \n",
      "3              95     3   0.000  ...               0.0      9              0   \n",
      "4              93     4   0.000  ...               0.0      9              0   \n",
      "...           ...   ...     ...  ...               ...    ...            ...   \n",
      "11011         100    19   1.693  ...               0.0     12              0   \n",
      "11012         100    20   1.327  ...               0.0     12              0   \n",
      "11013         100    21   0.757  ...               0.0     12              0   \n",
      "11014         100    22   0.000  ...               0.0     12              0   \n",
      "11015         100    23   0.000  ...               0.0     12              0   \n",
      "\n",
      "       few clouds  heavy intensity rain  light rain  moderate rain  \\\n",
      "0               0                     0           0              0   \n",
      "1               0                     0           0              0   \n",
      "2               0                     0           0              0   \n",
      "3               0                     0           0              0   \n",
      "4               0                     0           0              0   \n",
      "...           ...                   ...         ...            ...   \n",
      "11011           0                     0           0              1   \n",
      "11012           0                     1           0              0   \n",
      "11013           0                     1           0              0   \n",
      "11014           0                     0           0              1   \n",
      "11015           0                     1           0              0   \n",
      "\n",
      "       overcast clouds  scattered clouds  sky is clear  \n",
      "0                    1                 0             0  \n",
      "1                    1                 0             0  \n",
      "2                    1                 0             0  \n",
      "3                    1                 0             0  \n",
      "4                    1                 0             0  \n",
      "...                ...               ...           ...  \n",
      "11011                0                 0             0  \n",
      "11012                0                 0             0  \n",
      "11013                0                 0             0  \n",
      "11014                0                 0             0  \n",
      "11015                0                 0             0  \n",
      "\n",
      "[11016 rows x 21 columns]\n",
      "0        3\n",
      "1        3\n",
      "2        3\n",
      "3        3\n",
      "4        3\n",
      "        ..\n",
      "11011    3\n",
      "11012    3\n",
      "11013    3\n",
      "11014    3\n",
      "11015    3\n",
      "Name: injection_encoded, Length: 11016, dtype: int64\n"
     ]
    }
   ],
   "source": [
    "print(X)\n",
    "print(y)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 55,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Fitting 2 folds for each of 3 candidates, totalling 6 fits\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.\n",
      "  X, y = self._initialize(X, y)\n",
      "2023-12-18 19:35:01.630065: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at sparse_xent_op.cc:103 : INVALID_ARGUMENT: Received a label value of 4 which is outside the valid range of [0, 1).  Label values: 3 3 3 4 0 3 3 0 3 3 4 0 4 3 3 3 3 3 3 3 3 3 4 3 2 2 3 4 0 3 4 3\n",
      "/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.\n",
      "  X, y = self._initialize(X, y)\n",
      "2023-12-18 19:35:02.012413: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at sparse_xent_op.cc:103 : INVALID_ARGUMENT: Received a label value of 4 which is outside the valid range of [0, 1).  Label values: 3 3 3 4 3 2 2 3 3 4 3 2 3 0 3 2 3 3 2 3 4 3 0 3 3 3 3 3 3 3 1 4\n",
      "/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.\n",
      "  X, y = self._initialize(X, y)\n",
      "2023-12-18 19:35:02.379345: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at sparse_xent_op.cc:103 : INVALID_ARGUMENT: Received a label value of 4 which is outside the valid range of [0, 1).  Label values: 2 2 3 3 3 3 3 3 3 3 0 3 3 3 3 4 3 3 0 3 3 3 3 3 4 3 0 1 3 3 1 3\n",
      "/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.\n",
      "  X, y = self._initialize(X, y)\n",
      "2023-12-18 19:35:02.766596: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at sparse_xent_op.cc:103 : INVALID_ARGUMENT: Received a label value of 4 which is outside the valid range of [0, 1).  Label values: 3 3 3 2 3 2 3 3 2 3 3 3 3 3 3 3 3 3 3 4 3 4 3 0 3 4 0 3 3 3 3 3\n",
      "/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.\n",
      "  X, y = self._initialize(X, y)\n",
      "2023-12-18 19:35:03.135995: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at sparse_xent_op.cc:103 : INVALID_ARGUMENT: Received a label value of 4 which is outside the valid range of [0, 1).  Label values: 3 3 3 3 3 3 3 3 3 3 0 3 3 3 3 2 0 3 2 4 3 0 3 1 0 3 3 3 1 3 2 3\n",
      "/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py:915: UserWarning: ``build_fn`` will be renamed to ``model`` in a future release, at which point use of ``build_fn`` will raise an Error instead.\n",
      "  X, y = self._initialize(X, y)\n",
      "2023-12-18 19:35:03.516011: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at sparse_xent_op.cc:103 : INVALID_ARGUMENT: Received a label value of 4 which is outside the valid range of [0, 1).  Label values: 3 3 0 1 2 3 3 3 3 4 3 3 3 3 4 3 2 3 3 3 3 3 2 3 2 3 3 4 3 3 2 1\n"
     ]
    },
    {
     "ename": "ValueError",
     "evalue": "\nAll the 6 fits failed.\nIt is very likely that your model is misconfigured.\nYou can try to debug the error by setting error_score='raise'.\n\nBelow are more details about the failures:\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 732, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1491, in fit\n    super().fit(X=X, y=y, sample_weight=sample_weight, **kwargs)\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 760, in fit\n    self._fit(\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 928, in _fit\n    self._fit_keras_model(\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 524, in _fit_keras_model\n    hist = self.model_.fit(x=X, y=y, **fit_args)\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/tensorflow/python/eager/execute.py\", line 52, in quick_execute\n    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:\n\nDetected at node 'sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits' defined at (most recent call last):\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/runpy.py\", line 86, in _run_code\n      exec(code, run_globals)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel_launcher.py\", line 17, in <module>\n      app.launch_new_instance()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/traitlets/config/application.py\", line 992, in launch_instance\n      app.start()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 736, in start\n      self.io_loop.start()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 195, in start\n      self.asyncio_loop.run_forever()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n      self._run_once()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n      handle._run()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/asyncio/events.py\", line 80, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 516, in dispatch_queue\n      await self.process_one()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 505, in process_one\n      await dispatch(*args)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 412, in dispatch_shell\n      await result\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 740, in execute_request\n      reply_content = await reply_content\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n      res = shell.run_cell(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 546, in run_cell\n      return super().run_cell(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3024, in run_cell\n      result = self._run_cell(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3079, in _run_cell\n      result = runner(coro)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n      coro.send(None)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3284, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3466, in run_ast_nodes\n      if await self.run_code(code, result, async_=asy):\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3526, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"/var/folders/st/bgnz1xgs2hz0_cqmkbxt25r00000gn/T/ipykernel_12014/150609288.py\", line 1, in <module>\n      grid_search.fit(X,y)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/base.py\", line 1151, in wrapper\n      return fit_method(estimator, *args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_search.py\", line 898, in fit\n      self._run_search(evaluate_candidates)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_search.py\", line 1419, in _run_search\n      evaluate_candidates(ParameterGrid(self.param_grid))\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_search.py\", line 845, in evaluate_candidates\n      out = parallel(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n      return super().__call__(iterable_with_config)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 1085, in __call__\n      if self.dispatch_one_batch(iterator):\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 901, in dispatch_one_batch\n      self._dispatch(tasks)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 819, in _dispatch\n      job = self._backend.apply_async(batch, callback=cb)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/_parallel_backends.py\", line 208, in apply_async\n      result = ImmediateResult(func)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/_parallel_backends.py\", line 597, in __init__\n      self.results = batch()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 288, in __call__\n      return [func(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 288, in <listcomp>\n      return [func(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n      return self.function(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 732, in _fit_and_score\n      estimator.fit(X_train, y_train, **fit_params)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1491, in fit\n      super().fit(X=X, y=y, sample_weight=sample_weight, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 760, in fit\n      self._fit(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 928, in _fit\n      self._fit_keras_model(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 524, in _fit_keras_model\n      hist = self.model_.fit(x=X, y=y, **fit_args)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1650, in fit\n      tmp_logs = self.train_function(iterator)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1249, in train_function\n      return step_function(self, iterator)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1233, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1222, in run_step\n      outputs = model.train_step(data)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1024, in train_step\n      loss = self.compute_loss(x, y, y_pred, sample_weight)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1082, in compute_loss\n      return self.compiled_loss(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/compile_utils.py\", line 265, in __call__\n      loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/losses.py\", line 152, in __call__\n      losses = call_fn(y_true, y_pred)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/losses.py\", line 284, in call\n      return ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/losses.py\", line 2098, in sparse_categorical_crossentropy\n      return backend.sparse_categorical_crossentropy(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/backend.py\", line 5633, in sparse_categorical_crossentropy\n      res = tf.nn.sparse_softmax_cross_entropy_with_logits(\nNode: 'sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits'\nReceived a label value of 4 which is outside the valid range of [0, 1).  Label values: 3 3 3 4 0 3 3 0 3 3 4 0 4 3 3 3 3 3 3 3 3 3 4 3 2 2 3 4 0 3 4 3\n\t [[{{node sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits}}]] [Op:__inference_train_function_6021]\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 732, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1491, in fit\n    super().fit(X=X, y=y, sample_weight=sample_weight, **kwargs)\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 760, in fit\n    self._fit(\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 928, in _fit\n    self._fit_keras_model(\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 524, in _fit_keras_model\n    hist = self.model_.fit(x=X, y=y, **fit_args)\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/tensorflow/python/eager/execute.py\", line 52, in quick_execute\n    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:\n\nDetected at node 'sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits' defined at (most recent call last):\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/runpy.py\", line 86, in _run_code\n      exec(code, run_globals)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel_launcher.py\", line 17, in <module>\n      app.launch_new_instance()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/traitlets/config/application.py\", line 992, in launch_instance\n      app.start()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 736, in start\n      self.io_loop.start()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 195, in start\n      self.asyncio_loop.run_forever()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n      self._run_once()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n      handle._run()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/asyncio/events.py\", line 80, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 516, in dispatch_queue\n      await self.process_one()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 505, in process_one\n      await dispatch(*args)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 412, in dispatch_shell\n      await result\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 740, in execute_request\n      reply_content = await reply_content\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n      res = shell.run_cell(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 546, in run_cell\n      return super().run_cell(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3024, in run_cell\n      result = self._run_cell(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3079, in _run_cell\n      result = runner(coro)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n      coro.send(None)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3284, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3466, in run_ast_nodes\n      if await self.run_code(code, result, async_=asy):\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3526, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"/var/folders/st/bgnz1xgs2hz0_cqmkbxt25r00000gn/T/ipykernel_12014/150609288.py\", line 1, in <module>\n      grid_search.fit(X,y)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/base.py\", line 1151, in wrapper\n      return fit_method(estimator, *args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_search.py\", line 898, in fit\n      self._run_search(evaluate_candidates)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_search.py\", line 1419, in _run_search\n      evaluate_candidates(ParameterGrid(self.param_grid))\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_search.py\", line 845, in evaluate_candidates\n      out = parallel(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n      return super().__call__(iterable_with_config)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 1088, in __call__\n      while self.dispatch_one_batch(iterator):\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 901, in dispatch_one_batch\n      self._dispatch(tasks)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 819, in _dispatch\n      job = self._backend.apply_async(batch, callback=cb)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/_parallel_backends.py\", line 208, in apply_async\n      result = ImmediateResult(func)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/_parallel_backends.py\", line 597, in __init__\n      self.results = batch()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 288, in __call__\n      return [func(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 288, in <listcomp>\n      return [func(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n      return self.function(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 732, in _fit_and_score\n      estimator.fit(X_train, y_train, **fit_params)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1491, in fit\n      super().fit(X=X, y=y, sample_weight=sample_weight, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 760, in fit\n      self._fit(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 928, in _fit\n      self._fit_keras_model(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 524, in _fit_keras_model\n      hist = self.model_.fit(x=X, y=y, **fit_args)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1650, in fit\n      tmp_logs = self.train_function(iterator)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1249, in train_function\n      return step_function(self, iterator)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1233, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1222, in run_step\n      outputs = model.train_step(data)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1024, in train_step\n      loss = self.compute_loss(x, y, y_pred, sample_weight)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1082, in compute_loss\n      return self.compiled_loss(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/compile_utils.py\", line 265, in __call__\n      loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/losses.py\", line 152, in __call__\n      losses = call_fn(y_true, y_pred)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/losses.py\", line 284, in call\n      return ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/losses.py\", line 2098, in sparse_categorical_crossentropy\n      return backend.sparse_categorical_crossentropy(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/backend.py\", line 5633, in sparse_categorical_crossentropy\n      res = tf.nn.sparse_softmax_cross_entropy_with_logits(\nNode: 'sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits'\nReceived a label value of 4 which is outside the valid range of [0, 1).  Label values: 3 3 3 4 3 2 2 3 3 4 3 2 3 0 3 2 3 3 2 3 4 3 0 3 3 3 3 3 3 3 1 4\n\t [[{{node sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits}}]] [Op:__inference_train_function_7022]\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 732, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1491, in fit\n    super().fit(X=X, y=y, sample_weight=sample_weight, **kwargs)\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 760, in fit\n    self._fit(\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 928, in _fit\n    self._fit_keras_model(\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 524, in _fit_keras_model\n    hist = self.model_.fit(x=X, y=y, **fit_args)\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/tensorflow/python/eager/execute.py\", line 52, in quick_execute\n    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:\n\nDetected at node 'sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits' defined at (most recent call last):\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/runpy.py\", line 86, in _run_code\n      exec(code, run_globals)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel_launcher.py\", line 17, in <module>\n      app.launch_new_instance()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/traitlets/config/application.py\", line 992, in launch_instance\n      app.start()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 736, in start\n      self.io_loop.start()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 195, in start\n      self.asyncio_loop.run_forever()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n      self._run_once()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n      handle._run()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/asyncio/events.py\", line 80, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 516, in dispatch_queue\n      await self.process_one()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 505, in process_one\n      await dispatch(*args)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 412, in dispatch_shell\n      await result\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 740, in execute_request\n      reply_content = await reply_content\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n      res = shell.run_cell(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 546, in run_cell\n      return super().run_cell(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3024, in run_cell\n      result = self._run_cell(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3079, in _run_cell\n      result = runner(coro)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n      coro.send(None)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3284, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3466, in run_ast_nodes\n      if await self.run_code(code, result, async_=asy):\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3526, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"/var/folders/st/bgnz1xgs2hz0_cqmkbxt25r00000gn/T/ipykernel_12014/150609288.py\", line 1, in <module>\n      grid_search.fit(X,y)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/base.py\", line 1151, in wrapper\n      return fit_method(estimator, *args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_search.py\", line 898, in fit\n      self._run_search(evaluate_candidates)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_search.py\", line 1419, in _run_search\n      evaluate_candidates(ParameterGrid(self.param_grid))\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_search.py\", line 845, in evaluate_candidates\n      out = parallel(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n      return super().__call__(iterable_with_config)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 1088, in __call__\n      while self.dispatch_one_batch(iterator):\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 901, in dispatch_one_batch\n      self._dispatch(tasks)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 819, in _dispatch\n      job = self._backend.apply_async(batch, callback=cb)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/_parallel_backends.py\", line 208, in apply_async\n      result = ImmediateResult(func)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/_parallel_backends.py\", line 597, in __init__\n      self.results = batch()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 288, in __call__\n      return [func(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 288, in <listcomp>\n      return [func(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n      return self.function(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 732, in _fit_and_score\n      estimator.fit(X_train, y_train, **fit_params)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1491, in fit\n      super().fit(X=X, y=y, sample_weight=sample_weight, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 760, in fit\n      self._fit(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 928, in _fit\n      self._fit_keras_model(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 524, in _fit_keras_model\n      hist = self.model_.fit(x=X, y=y, **fit_args)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1650, in fit\n      tmp_logs = self.train_function(iterator)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1249, in train_function\n      return step_function(self, iterator)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1233, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1222, in run_step\n      outputs = model.train_step(data)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1024, in train_step\n      loss = self.compute_loss(x, y, y_pred, sample_weight)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1082, in compute_loss\n      return self.compiled_loss(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/compile_utils.py\", line 265, in __call__\n      loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/losses.py\", line 152, in __call__\n      losses = call_fn(y_true, y_pred)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/losses.py\", line 284, in call\n      return ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/losses.py\", line 2098, in sparse_categorical_crossentropy\n      return backend.sparse_categorical_crossentropy(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/backend.py\", line 5633, in sparse_categorical_crossentropy\n      res = tf.nn.sparse_softmax_cross_entropy_with_logits(\nNode: 'sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits'\nReceived a label value of 4 which is outside the valid range of [0, 1).  Label values: 2 2 3 3 3 3 3 3 3 3 0 3 3 3 3 4 3 3 0 3 3 3 3 3 4 3 0 1 3 3 1 3\n\t [[{{node sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits}}]] [Op:__inference_train_function_8023]\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 732, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1491, in fit\n    super().fit(X=X, y=y, sample_weight=sample_weight, **kwargs)\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 760, in fit\n    self._fit(\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 928, in _fit\n    self._fit_keras_model(\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 524, in _fit_keras_model\n    hist = self.model_.fit(x=X, y=y, **fit_args)\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/tensorflow/python/eager/execute.py\", line 52, in quick_execute\n    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:\n\nDetected at node 'sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits' defined at (most recent call last):\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/runpy.py\", line 86, in _run_code\n      exec(code, run_globals)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel_launcher.py\", line 17, in <module>\n      app.launch_new_instance()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/traitlets/config/application.py\", line 992, in launch_instance\n      app.start()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 736, in start\n      self.io_loop.start()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 195, in start\n      self.asyncio_loop.run_forever()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n      self._run_once()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n      handle._run()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/asyncio/events.py\", line 80, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 516, in dispatch_queue\n      await self.process_one()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 505, in process_one\n      await dispatch(*args)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 412, in dispatch_shell\n      await result\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 740, in execute_request\n      reply_content = await reply_content\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n      res = shell.run_cell(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 546, in run_cell\n      return super().run_cell(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3024, in run_cell\n      result = self._run_cell(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3079, in _run_cell\n      result = runner(coro)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n      coro.send(None)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3284, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3466, in run_ast_nodes\n      if await self.run_code(code, result, async_=asy):\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3526, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"/var/folders/st/bgnz1xgs2hz0_cqmkbxt25r00000gn/T/ipykernel_12014/150609288.py\", line 1, in <module>\n      grid_search.fit(X,y)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/base.py\", line 1151, in wrapper\n      return fit_method(estimator, *args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_search.py\", line 898, in fit\n      self._run_search(evaluate_candidates)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_search.py\", line 1419, in _run_search\n      evaluate_candidates(ParameterGrid(self.param_grid))\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_search.py\", line 845, in evaluate_candidates\n      out = parallel(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n      return super().__call__(iterable_with_config)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 1088, in __call__\n      while self.dispatch_one_batch(iterator):\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 901, in dispatch_one_batch\n      self._dispatch(tasks)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 819, in _dispatch\n      job = self._backend.apply_async(batch, callback=cb)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/_parallel_backends.py\", line 208, in apply_async\n      result = ImmediateResult(func)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/_parallel_backends.py\", line 597, in __init__\n      self.results = batch()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 288, in __call__\n      return [func(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 288, in <listcomp>\n      return [func(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n      return self.function(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 732, in _fit_and_score\n      estimator.fit(X_train, y_train, **fit_params)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1491, in fit\n      super().fit(X=X, y=y, sample_weight=sample_weight, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 760, in fit\n      self._fit(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 928, in _fit\n      self._fit_keras_model(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 524, in _fit_keras_model\n      hist = self.model_.fit(x=X, y=y, **fit_args)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1650, in fit\n      tmp_logs = self.train_function(iterator)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1249, in train_function\n      return step_function(self, iterator)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1233, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1222, in run_step\n      outputs = model.train_step(data)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1024, in train_step\n      loss = self.compute_loss(x, y, y_pred, sample_weight)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1082, in compute_loss\n      return self.compiled_loss(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/compile_utils.py\", line 265, in __call__\n      loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/losses.py\", line 152, in __call__\n      losses = call_fn(y_true, y_pred)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/losses.py\", line 284, in call\n      return ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/losses.py\", line 2098, in sparse_categorical_crossentropy\n      return backend.sparse_categorical_crossentropy(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/backend.py\", line 5633, in sparse_categorical_crossentropy\n      res = tf.nn.sparse_softmax_cross_entropy_with_logits(\nNode: 'sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits'\nReceived a label value of 4 which is outside the valid range of [0, 1).  Label values: 3 3 3 2 3 2 3 3 2 3 3 3 3 3 3 3 3 3 3 4 3 4 3 0 3 4 0 3 3 3 3 3\n\t [[{{node sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits}}]] [Op:__inference_train_function_9024]\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 732, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1491, in fit\n    super().fit(X=X, y=y, sample_weight=sample_weight, **kwargs)\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 760, in fit\n    self._fit(\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 928, in _fit\n    self._fit_keras_model(\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 524, in _fit_keras_model\n    hist = self.model_.fit(x=X, y=y, **fit_args)\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/tensorflow/python/eager/execute.py\", line 52, in quick_execute\n    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:\n\nDetected at node 'sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits' defined at (most recent call last):\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/runpy.py\", line 86, in _run_code\n      exec(code, run_globals)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel_launcher.py\", line 17, in <module>\n      app.launch_new_instance()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/traitlets/config/application.py\", line 992, in launch_instance\n      app.start()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 736, in start\n      self.io_loop.start()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 195, in start\n      self.asyncio_loop.run_forever()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n      self._run_once()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n      handle._run()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/asyncio/events.py\", line 80, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 516, in dispatch_queue\n      await self.process_one()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 505, in process_one\n      await dispatch(*args)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 412, in dispatch_shell\n      await result\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 740, in execute_request\n      reply_content = await reply_content\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n      res = shell.run_cell(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 546, in run_cell\n      return super().run_cell(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3024, in run_cell\n      result = self._run_cell(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3079, in _run_cell\n      result = runner(coro)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n      coro.send(None)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3284, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3466, in run_ast_nodes\n      if await self.run_code(code, result, async_=asy):\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3526, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"/var/folders/st/bgnz1xgs2hz0_cqmkbxt25r00000gn/T/ipykernel_12014/150609288.py\", line 1, in <module>\n      grid_search.fit(X,y)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/base.py\", line 1151, in wrapper\n      return fit_method(estimator, *args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_search.py\", line 898, in fit\n      self._run_search(evaluate_candidates)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_search.py\", line 1419, in _run_search\n      evaluate_candidates(ParameterGrid(self.param_grid))\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_search.py\", line 845, in evaluate_candidates\n      out = parallel(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n      return super().__call__(iterable_with_config)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 1088, in __call__\n      while self.dispatch_one_batch(iterator):\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 901, in dispatch_one_batch\n      self._dispatch(tasks)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 819, in _dispatch\n      job = self._backend.apply_async(batch, callback=cb)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/_parallel_backends.py\", line 208, in apply_async\n      result = ImmediateResult(func)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/_parallel_backends.py\", line 597, in __init__\n      self.results = batch()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 288, in __call__\n      return [func(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 288, in <listcomp>\n      return [func(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n      return self.function(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 732, in _fit_and_score\n      estimator.fit(X_train, y_train, **fit_params)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1491, in fit\n      super().fit(X=X, y=y, sample_weight=sample_weight, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 760, in fit\n      self._fit(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 928, in _fit\n      self._fit_keras_model(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 524, in _fit_keras_model\n      hist = self.model_.fit(x=X, y=y, **fit_args)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1650, in fit\n      tmp_logs = self.train_function(iterator)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1249, in train_function\n      return step_function(self, iterator)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1233, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1222, in run_step\n      outputs = model.train_step(data)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1024, in train_step\n      loss = self.compute_loss(x, y, y_pred, sample_weight)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1082, in compute_loss\n      return self.compiled_loss(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/compile_utils.py\", line 265, in __call__\n      loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/losses.py\", line 152, in __call__\n      losses = call_fn(y_true, y_pred)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/losses.py\", line 284, in call\n      return ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/losses.py\", line 2098, in sparse_categorical_crossentropy\n      return backend.sparse_categorical_crossentropy(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/backend.py\", line 5633, in sparse_categorical_crossentropy\n      res = tf.nn.sparse_softmax_cross_entropy_with_logits(\nNode: 'sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits'\nReceived a label value of 4 which is outside the valid range of [0, 1).  Label values: 3 3 3 3 3 3 3 3 3 3 0 3 3 3 3 2 0 3 2 4 3 0 3 1 0 3 3 3 1 3 2 3\n\t [[{{node sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits}}]] [Op:__inference_train_function_10025]\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 732, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1491, in fit\n    super().fit(X=X, y=y, sample_weight=sample_weight, **kwargs)\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 760, in fit\n    self._fit(\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 928, in _fit\n    self._fit_keras_model(\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 524, in _fit_keras_model\n    hist = self.model_.fit(x=X, y=y, **fit_args)\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/tensorflow/python/eager/execute.py\", line 52, in quick_execute\n    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:\n\nDetected at node 'sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits' defined at (most recent call last):\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/runpy.py\", line 86, in _run_code\n      exec(code, run_globals)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel_launcher.py\", line 17, in <module>\n      app.launch_new_instance()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/traitlets/config/application.py\", line 992, in launch_instance\n      app.start()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 736, in start\n      self.io_loop.start()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 195, in start\n      self.asyncio_loop.run_forever()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n      self._run_once()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n      handle._run()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/asyncio/events.py\", line 80, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 516, in dispatch_queue\n      await self.process_one()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 505, in process_one\n      await dispatch(*args)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 412, in dispatch_shell\n      await result\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 740, in execute_request\n      reply_content = await reply_content\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n      res = shell.run_cell(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 546, in run_cell\n      return super().run_cell(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3024, in run_cell\n      result = self._run_cell(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3079, in _run_cell\n      result = runner(coro)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n      coro.send(None)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3284, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3466, in run_ast_nodes\n      if await self.run_code(code, result, async_=asy):\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3526, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"/var/folders/st/bgnz1xgs2hz0_cqmkbxt25r00000gn/T/ipykernel_12014/150609288.py\", line 1, in <module>\n      grid_search.fit(X,y)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/base.py\", line 1151, in wrapper\n      return fit_method(estimator, *args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_search.py\", line 898, in fit\n      self._run_search(evaluate_candidates)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_search.py\", line 1419, in _run_search\n      evaluate_candidates(ParameterGrid(self.param_grid))\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_search.py\", line 845, in evaluate_candidates\n      out = parallel(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n      return super().__call__(iterable_with_config)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 1088, in __call__\n      while self.dispatch_one_batch(iterator):\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 901, in dispatch_one_batch\n      self._dispatch(tasks)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 819, in _dispatch\n      job = self._backend.apply_async(batch, callback=cb)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/_parallel_backends.py\", line 208, in apply_async\n      result = ImmediateResult(func)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/_parallel_backends.py\", line 597, in __init__\n      self.results = batch()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 288, in __call__\n      return [func(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 288, in <listcomp>\n      return [func(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n      return self.function(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 732, in _fit_and_score\n      estimator.fit(X_train, y_train, **fit_params)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1491, in fit\n      super().fit(X=X, y=y, sample_weight=sample_weight, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 760, in fit\n      self._fit(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 928, in _fit\n      self._fit_keras_model(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 524, in _fit_keras_model\n      hist = self.model_.fit(x=X, y=y, **fit_args)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1650, in fit\n      tmp_logs = self.train_function(iterator)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1249, in train_function\n      return step_function(self, iterator)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1233, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1222, in run_step\n      outputs = model.train_step(data)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1024, in train_step\n      loss = self.compute_loss(x, y, y_pred, sample_weight)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1082, in compute_loss\n      return self.compiled_loss(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/compile_utils.py\", line 265, in __call__\n      loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/losses.py\", line 152, in __call__\n      losses = call_fn(y_true, y_pred)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/losses.py\", line 284, in call\n      return ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/losses.py\", line 2098, in sparse_categorical_crossentropy\n      return backend.sparse_categorical_crossentropy(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/backend.py\", line 5633, in sparse_categorical_crossentropy\n      res = tf.nn.sparse_softmax_cross_entropy_with_logits(\nNode: 'sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits'\nReceived a label value of 4 which is outside the valid range of [0, 1).  Label values: 3 3 0 1 2 3 3 3 3 4 3 3 3 3 4 3 2 3 3 3 3 3 2 3 2 3 3 4 3 3 2 1\n\t [[{{node sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits}}]] [Op:__inference_train_function_11026]\n",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[55], line 1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m \u001b[43mgrid_search\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mfit\u001b[49m\u001b[43m(\u001b[49m\u001b[43mX\u001b[49m\u001b[43m,\u001b[49m\u001b[43my\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/base.py:1151\u001b[0m, in \u001b[0;36m_fit_context.<locals>.decorator.<locals>.wrapper\u001b[0;34m(estimator, *args, **kwargs)\u001b[0m\n\u001b[1;32m   1144\u001b[0m     estimator\u001b[38;5;241m.\u001b[39m_validate_params()\n\u001b[1;32m   1146\u001b[0m \u001b[38;5;28;01mwith\u001b[39;00m config_context(\n\u001b[1;32m   1147\u001b[0m     skip_parameter_validation\u001b[38;5;241m=\u001b[39m(\n\u001b[1;32m   1148\u001b[0m         prefer_skip_nested_validation \u001b[38;5;129;01mor\u001b[39;00m global_skip_validation\n\u001b[1;32m   1149\u001b[0m     )\n\u001b[1;32m   1150\u001b[0m ):\n\u001b[0;32m-> 1151\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mfit_method\u001b[49m\u001b[43m(\u001b[49m\u001b[43mestimator\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_search.py:898\u001b[0m, in \u001b[0;36mBaseSearchCV.fit\u001b[0;34m(self, X, y, groups, **fit_params)\u001b[0m\n\u001b[1;32m    892\u001b[0m     results \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_format_results(\n\u001b[1;32m    893\u001b[0m         all_candidate_params, n_splits, all_out, all_more_results\n\u001b[1;32m    894\u001b[0m     )\n\u001b[1;32m    896\u001b[0m     \u001b[38;5;28;01mreturn\u001b[39;00m results\n\u001b[0;32m--> 898\u001b[0m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_run_search\u001b[49m\u001b[43m(\u001b[49m\u001b[43mevaluate_candidates\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    900\u001b[0m \u001b[38;5;66;03m# multimetric is determined here because in the case of a callable\u001b[39;00m\n\u001b[1;32m    901\u001b[0m \u001b[38;5;66;03m# self.scoring the return type is only known after calling\u001b[39;00m\n\u001b[1;32m    902\u001b[0m first_test_score \u001b[38;5;241m=\u001b[39m all_out[\u001b[38;5;241m0\u001b[39m][\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mtest_scores\u001b[39m\u001b[38;5;124m\"\u001b[39m]\n",
      "File \u001b[0;32m~/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_search.py:1419\u001b[0m, in \u001b[0;36mGridSearchCV._run_search\u001b[0;34m(self, evaluate_candidates)\u001b[0m\n\u001b[1;32m   1417\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21m_run_search\u001b[39m(\u001b[38;5;28mself\u001b[39m, evaluate_candidates):\n\u001b[1;32m   1418\u001b[0m \u001b[38;5;250m    \u001b[39m\u001b[38;5;124;03m\"\"\"Search all candidates in param_grid\"\"\"\u001b[39;00m\n\u001b[0;32m-> 1419\u001b[0m     \u001b[43mevaluate_candidates\u001b[49m\u001b[43m(\u001b[49m\u001b[43mParameterGrid\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mparam_grid\u001b[49m\u001b[43m)\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_search.py:875\u001b[0m, in \u001b[0;36mBaseSearchCV.fit.<locals>.evaluate_candidates\u001b[0;34m(candidate_params, cv, more_results)\u001b[0m\n\u001b[1;32m    868\u001b[0m \u001b[38;5;28;01melif\u001b[39;00m \u001b[38;5;28mlen\u001b[39m(out) \u001b[38;5;241m!=\u001b[39m n_candidates \u001b[38;5;241m*\u001b[39m n_splits:\n\u001b[1;32m    869\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mValueError\u001b[39;00m(\n\u001b[1;32m    870\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mcv.split and cv.get_n_splits returned \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    871\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124minconsistent results. Expected \u001b[39m\u001b[38;5;132;01m{}\u001b[39;00m\u001b[38;5;124m \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    872\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124msplits, got \u001b[39m\u001b[38;5;132;01m{}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;241m.\u001b[39mformat(n_splits, \u001b[38;5;28mlen\u001b[39m(out) \u001b[38;5;241m/\u001b[39m\u001b[38;5;241m/\u001b[39m n_candidates)\n\u001b[1;32m    873\u001b[0m     )\n\u001b[0;32m--> 875\u001b[0m \u001b[43m_warn_or_raise_about_fit_failures\u001b[49m\u001b[43m(\u001b[49m\u001b[43mout\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43merror_score\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    877\u001b[0m \u001b[38;5;66;03m# For callable self.scoring, the return type is only know after\u001b[39;00m\n\u001b[1;32m    878\u001b[0m \u001b[38;5;66;03m# calling. If the return type is a dictionary, the error scores\u001b[39;00m\n\u001b[1;32m    879\u001b[0m \u001b[38;5;66;03m# can now be inserted with the correct key. The type checking\u001b[39;00m\n\u001b[1;32m    880\u001b[0m \u001b[38;5;66;03m# of out will be done in `_insert_error_scores`.\u001b[39;00m\n\u001b[1;32m    881\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mcallable\u001b[39m(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mscoring):\n",
      "File \u001b[0;32m~/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:414\u001b[0m, in \u001b[0;36m_warn_or_raise_about_fit_failures\u001b[0;34m(results, error_score)\u001b[0m\n\u001b[1;32m    407\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m num_failed_fits \u001b[38;5;241m==\u001b[39m num_fits:\n\u001b[1;32m    408\u001b[0m     all_fits_failed_message \u001b[38;5;241m=\u001b[39m (\n\u001b[1;32m    409\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124mAll the \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mnum_fits\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m fits failed.\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    410\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mIt is very likely that your model is misconfigured.\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    411\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mYou can try to debug the error by setting error_score=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mraise\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m.\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    412\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mBelow are more details about the failures:\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;132;01m{\u001b[39;00mfit_errors_summary\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    413\u001b[0m     )\n\u001b[0;32m--> 414\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mValueError\u001b[39;00m(all_fits_failed_message)\n\u001b[1;32m    416\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m    417\u001b[0m     some_fits_failed_message \u001b[38;5;241m=\u001b[39m (\n\u001b[1;32m    418\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;132;01m{\u001b[39;00mnum_failed_fits\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m fits failed out of a total of \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mnum_fits\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m.\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    419\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mThe score on these train-test partitions for these parameters\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    423\u001b[0m         \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mBelow are more details about the failures:\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;132;01m{\u001b[39;00mfit_errors_summary\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m    424\u001b[0m     )\n",
      "\u001b[0;31mValueError\u001b[0m: \nAll the 6 fits failed.\nIt is very likely that your model is misconfigured.\nYou can try to debug the error by setting error_score='raise'.\n\nBelow are more details about the failures:\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 732, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1491, in fit\n    super().fit(X=X, y=y, sample_weight=sample_weight, **kwargs)\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 760, in fit\n    self._fit(\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 928, in _fit\n    self._fit_keras_model(\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 524, in _fit_keras_model\n    hist = self.model_.fit(x=X, y=y, **fit_args)\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/tensorflow/python/eager/execute.py\", line 52, in quick_execute\n    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:\n\nDetected at node 'sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits' defined at (most recent call last):\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/runpy.py\", line 86, in _run_code\n      exec(code, run_globals)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel_launcher.py\", line 17, in <module>\n      app.launch_new_instance()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/traitlets/config/application.py\", line 992, in launch_instance\n      app.start()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 736, in start\n      self.io_loop.start()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 195, in start\n      self.asyncio_loop.run_forever()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n      self._run_once()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n      handle._run()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/asyncio/events.py\", line 80, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 516, in dispatch_queue\n      await self.process_one()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 505, in process_one\n      await dispatch(*args)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 412, in dispatch_shell\n      await result\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 740, in execute_request\n      reply_content = await reply_content\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n      res = shell.run_cell(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 546, in run_cell\n      return super().run_cell(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3024, in run_cell\n      result = self._run_cell(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3079, in _run_cell\n      result = runner(coro)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n      coro.send(None)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3284, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3466, in run_ast_nodes\n      if await self.run_code(code, result, async_=asy):\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3526, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"/var/folders/st/bgnz1xgs2hz0_cqmkbxt25r00000gn/T/ipykernel_12014/150609288.py\", line 1, in <module>\n      grid_search.fit(X,y)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/base.py\", line 1151, in wrapper\n      return fit_method(estimator, *args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_search.py\", line 898, in fit\n      self._run_search(evaluate_candidates)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_search.py\", line 1419, in _run_search\n      evaluate_candidates(ParameterGrid(self.param_grid))\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_search.py\", line 845, in evaluate_candidates\n      out = parallel(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n      return super().__call__(iterable_with_config)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 1085, in __call__\n      if self.dispatch_one_batch(iterator):\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 901, in dispatch_one_batch\n      self._dispatch(tasks)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 819, in _dispatch\n      job = self._backend.apply_async(batch, callback=cb)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/_parallel_backends.py\", line 208, in apply_async\n      result = ImmediateResult(func)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/_parallel_backends.py\", line 597, in __init__\n      self.results = batch()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 288, in __call__\n      return [func(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 288, in <listcomp>\n      return [func(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n      return self.function(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 732, in _fit_and_score\n      estimator.fit(X_train, y_train, **fit_params)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1491, in fit\n      super().fit(X=X, y=y, sample_weight=sample_weight, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 760, in fit\n      self._fit(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 928, in _fit\n      self._fit_keras_model(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 524, in _fit_keras_model\n      hist = self.model_.fit(x=X, y=y, **fit_args)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1650, in fit\n      tmp_logs = self.train_function(iterator)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1249, in train_function\n      return step_function(self, iterator)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1233, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1222, in run_step\n      outputs = model.train_step(data)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1024, in train_step\n      loss = self.compute_loss(x, y, y_pred, sample_weight)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1082, in compute_loss\n      return self.compiled_loss(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/compile_utils.py\", line 265, in __call__\n      loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/losses.py\", line 152, in __call__\n      losses = call_fn(y_true, y_pred)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/losses.py\", line 284, in call\n      return ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/losses.py\", line 2098, in sparse_categorical_crossentropy\n      return backend.sparse_categorical_crossentropy(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/backend.py\", line 5633, in sparse_categorical_crossentropy\n      res = tf.nn.sparse_softmax_cross_entropy_with_logits(\nNode: 'sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits'\nReceived a label value of 4 which is outside the valid range of [0, 1).  Label values: 3 3 3 4 0 3 3 0 3 3 4 0 4 3 3 3 3 3 3 3 3 3 4 3 2 2 3 4 0 3 4 3\n\t [[{{node sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits}}]] [Op:__inference_train_function_6021]\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 732, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1491, in fit\n    super().fit(X=X, y=y, sample_weight=sample_weight, **kwargs)\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 760, in fit\n    self._fit(\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 928, in _fit\n    self._fit_keras_model(\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 524, in _fit_keras_model\n    hist = self.model_.fit(x=X, y=y, **fit_args)\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/tensorflow/python/eager/execute.py\", line 52, in quick_execute\n    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:\n\nDetected at node 'sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits' defined at (most recent call last):\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/runpy.py\", line 86, in _run_code\n      exec(code, run_globals)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel_launcher.py\", line 17, in <module>\n      app.launch_new_instance()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/traitlets/config/application.py\", line 992, in launch_instance\n      app.start()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 736, in start\n      self.io_loop.start()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 195, in start\n      self.asyncio_loop.run_forever()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n      self._run_once()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n      handle._run()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/asyncio/events.py\", line 80, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 516, in dispatch_queue\n      await self.process_one()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 505, in process_one\n      await dispatch(*args)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 412, in dispatch_shell\n      await result\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 740, in execute_request\n      reply_content = await reply_content\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n      res = shell.run_cell(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 546, in run_cell\n      return super().run_cell(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3024, in run_cell\n      result = self._run_cell(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3079, in _run_cell\n      result = runner(coro)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n      coro.send(None)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3284, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3466, in run_ast_nodes\n      if await self.run_code(code, result, async_=asy):\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3526, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"/var/folders/st/bgnz1xgs2hz0_cqmkbxt25r00000gn/T/ipykernel_12014/150609288.py\", line 1, in <module>\n      grid_search.fit(X,y)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/base.py\", line 1151, in wrapper\n      return fit_method(estimator, *args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_search.py\", line 898, in fit\n      self._run_search(evaluate_candidates)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_search.py\", line 1419, in _run_search\n      evaluate_candidates(ParameterGrid(self.param_grid))\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_search.py\", line 845, in evaluate_candidates\n      out = parallel(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n      return super().__call__(iterable_with_config)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 1088, in __call__\n      while self.dispatch_one_batch(iterator):\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 901, in dispatch_one_batch\n      self._dispatch(tasks)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 819, in _dispatch\n      job = self._backend.apply_async(batch, callback=cb)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/_parallel_backends.py\", line 208, in apply_async\n      result = ImmediateResult(func)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/_parallel_backends.py\", line 597, in __init__\n      self.results = batch()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 288, in __call__\n      return [func(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 288, in <listcomp>\n      return [func(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n      return self.function(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 732, in _fit_and_score\n      estimator.fit(X_train, y_train, **fit_params)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1491, in fit\n      super().fit(X=X, y=y, sample_weight=sample_weight, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 760, in fit\n      self._fit(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 928, in _fit\n      self._fit_keras_model(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 524, in _fit_keras_model\n      hist = self.model_.fit(x=X, y=y, **fit_args)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1650, in fit\n      tmp_logs = self.train_function(iterator)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1249, in train_function\n      return step_function(self, iterator)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1233, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1222, in run_step\n      outputs = model.train_step(data)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1024, in train_step\n      loss = self.compute_loss(x, y, y_pred, sample_weight)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1082, in compute_loss\n      return self.compiled_loss(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/compile_utils.py\", line 265, in __call__\n      loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/losses.py\", line 152, in __call__\n      losses = call_fn(y_true, y_pred)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/losses.py\", line 284, in call\n      return ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/losses.py\", line 2098, in sparse_categorical_crossentropy\n      return backend.sparse_categorical_crossentropy(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/backend.py\", line 5633, in sparse_categorical_crossentropy\n      res = tf.nn.sparse_softmax_cross_entropy_with_logits(\nNode: 'sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits'\nReceived a label value of 4 which is outside the valid range of [0, 1).  Label values: 3 3 3 4 3 2 2 3 3 4 3 2 3 0 3 2 3 3 2 3 4 3 0 3 3 3 3 3 3 3 1 4\n\t [[{{node sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits}}]] [Op:__inference_train_function_7022]\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 732, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1491, in fit\n    super().fit(X=X, y=y, sample_weight=sample_weight, **kwargs)\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 760, in fit\n    self._fit(\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 928, in _fit\n    self._fit_keras_model(\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 524, in _fit_keras_model\n    hist = self.model_.fit(x=X, y=y, **fit_args)\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/tensorflow/python/eager/execute.py\", line 52, in quick_execute\n    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:\n\nDetected at node 'sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits' defined at (most recent call last):\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/runpy.py\", line 86, in _run_code\n      exec(code, run_globals)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel_launcher.py\", line 17, in <module>\n      app.launch_new_instance()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/traitlets/config/application.py\", line 992, in launch_instance\n      app.start()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 736, in start\n      self.io_loop.start()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 195, in start\n      self.asyncio_loop.run_forever()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n      self._run_once()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n      handle._run()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/asyncio/events.py\", line 80, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 516, in dispatch_queue\n      await self.process_one()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 505, in process_one\n      await dispatch(*args)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 412, in dispatch_shell\n      await result\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 740, in execute_request\n      reply_content = await reply_content\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n      res = shell.run_cell(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 546, in run_cell\n      return super().run_cell(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3024, in run_cell\n      result = self._run_cell(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3079, in _run_cell\n      result = runner(coro)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n      coro.send(None)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3284, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3466, in run_ast_nodes\n      if await self.run_code(code, result, async_=asy):\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3526, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"/var/folders/st/bgnz1xgs2hz0_cqmkbxt25r00000gn/T/ipykernel_12014/150609288.py\", line 1, in <module>\n      grid_search.fit(X,y)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/base.py\", line 1151, in wrapper\n      return fit_method(estimator, *args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_search.py\", line 898, in fit\n      self._run_search(evaluate_candidates)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_search.py\", line 1419, in _run_search\n      evaluate_candidates(ParameterGrid(self.param_grid))\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_search.py\", line 845, in evaluate_candidates\n      out = parallel(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n      return super().__call__(iterable_with_config)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 1088, in __call__\n      while self.dispatch_one_batch(iterator):\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 901, in dispatch_one_batch\n      self._dispatch(tasks)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 819, in _dispatch\n      job = self._backend.apply_async(batch, callback=cb)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/_parallel_backends.py\", line 208, in apply_async\n      result = ImmediateResult(func)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/_parallel_backends.py\", line 597, in __init__\n      self.results = batch()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 288, in __call__\n      return [func(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 288, in <listcomp>\n      return [func(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n      return self.function(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 732, in _fit_and_score\n      estimator.fit(X_train, y_train, **fit_params)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1491, in fit\n      super().fit(X=X, y=y, sample_weight=sample_weight, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 760, in fit\n      self._fit(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 928, in _fit\n      self._fit_keras_model(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 524, in _fit_keras_model\n      hist = self.model_.fit(x=X, y=y, **fit_args)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1650, in fit\n      tmp_logs = self.train_function(iterator)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1249, in train_function\n      return step_function(self, iterator)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1233, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1222, in run_step\n      outputs = model.train_step(data)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1024, in train_step\n      loss = self.compute_loss(x, y, y_pred, sample_weight)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1082, in compute_loss\n      return self.compiled_loss(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/compile_utils.py\", line 265, in __call__\n      loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/losses.py\", line 152, in __call__\n      losses = call_fn(y_true, y_pred)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/losses.py\", line 284, in call\n      return ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/losses.py\", line 2098, in sparse_categorical_crossentropy\n      return backend.sparse_categorical_crossentropy(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/backend.py\", line 5633, in sparse_categorical_crossentropy\n      res = tf.nn.sparse_softmax_cross_entropy_with_logits(\nNode: 'sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits'\nReceived a label value of 4 which is outside the valid range of [0, 1).  Label values: 2 2 3 3 3 3 3 3 3 3 0 3 3 3 3 4 3 3 0 3 3 3 3 3 4 3 0 1 3 3 1 3\n\t [[{{node sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits}}]] [Op:__inference_train_function_8023]\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 732, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1491, in fit\n    super().fit(X=X, y=y, sample_weight=sample_weight, **kwargs)\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 760, in fit\n    self._fit(\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 928, in _fit\n    self._fit_keras_model(\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 524, in _fit_keras_model\n    hist = self.model_.fit(x=X, y=y, **fit_args)\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/tensorflow/python/eager/execute.py\", line 52, in quick_execute\n    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:\n\nDetected at node 'sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits' defined at (most recent call last):\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/runpy.py\", line 86, in _run_code\n      exec(code, run_globals)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel_launcher.py\", line 17, in <module>\n      app.launch_new_instance()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/traitlets/config/application.py\", line 992, in launch_instance\n      app.start()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 736, in start\n      self.io_loop.start()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 195, in start\n      self.asyncio_loop.run_forever()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n      self._run_once()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n      handle._run()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/asyncio/events.py\", line 80, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 516, in dispatch_queue\n      await self.process_one()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 505, in process_one\n      await dispatch(*args)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 412, in dispatch_shell\n      await result\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 740, in execute_request\n      reply_content = await reply_content\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n      res = shell.run_cell(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 546, in run_cell\n      return super().run_cell(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3024, in run_cell\n      result = self._run_cell(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3079, in _run_cell\n      result = runner(coro)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n      coro.send(None)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3284, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3466, in run_ast_nodes\n      if await self.run_code(code, result, async_=asy):\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3526, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"/var/folders/st/bgnz1xgs2hz0_cqmkbxt25r00000gn/T/ipykernel_12014/150609288.py\", line 1, in <module>\n      grid_search.fit(X,y)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/base.py\", line 1151, in wrapper\n      return fit_method(estimator, *args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_search.py\", line 898, in fit\n      self._run_search(evaluate_candidates)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_search.py\", line 1419, in _run_search\n      evaluate_candidates(ParameterGrid(self.param_grid))\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_search.py\", line 845, in evaluate_candidates\n      out = parallel(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n      return super().__call__(iterable_with_config)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 1088, in __call__\n      while self.dispatch_one_batch(iterator):\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 901, in dispatch_one_batch\n      self._dispatch(tasks)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 819, in _dispatch\n      job = self._backend.apply_async(batch, callback=cb)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/_parallel_backends.py\", line 208, in apply_async\n      result = ImmediateResult(func)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/_parallel_backends.py\", line 597, in __init__\n      self.results = batch()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 288, in __call__\n      return [func(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 288, in <listcomp>\n      return [func(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n      return self.function(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 732, in _fit_and_score\n      estimator.fit(X_train, y_train, **fit_params)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1491, in fit\n      super().fit(X=X, y=y, sample_weight=sample_weight, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 760, in fit\n      self._fit(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 928, in _fit\n      self._fit_keras_model(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 524, in _fit_keras_model\n      hist = self.model_.fit(x=X, y=y, **fit_args)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1650, in fit\n      tmp_logs = self.train_function(iterator)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1249, in train_function\n      return step_function(self, iterator)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1233, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1222, in run_step\n      outputs = model.train_step(data)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1024, in train_step\n      loss = self.compute_loss(x, y, y_pred, sample_weight)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1082, in compute_loss\n      return self.compiled_loss(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/compile_utils.py\", line 265, in __call__\n      loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/losses.py\", line 152, in __call__\n      losses = call_fn(y_true, y_pred)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/losses.py\", line 284, in call\n      return ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/losses.py\", line 2098, in sparse_categorical_crossentropy\n      return backend.sparse_categorical_crossentropy(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/backend.py\", line 5633, in sparse_categorical_crossentropy\n      res = tf.nn.sparse_softmax_cross_entropy_with_logits(\nNode: 'sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits'\nReceived a label value of 4 which is outside the valid range of [0, 1).  Label values: 3 3 3 2 3 2 3 3 2 3 3 3 3 3 3 3 3 3 3 4 3 4 3 0 3 4 0 3 3 3 3 3\n\t [[{{node sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits}}]] [Op:__inference_train_function_9024]\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 732, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1491, in fit\n    super().fit(X=X, y=y, sample_weight=sample_weight, **kwargs)\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 760, in fit\n    self._fit(\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 928, in _fit\n    self._fit_keras_model(\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 524, in _fit_keras_model\n    hist = self.model_.fit(x=X, y=y, **fit_args)\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/tensorflow/python/eager/execute.py\", line 52, in quick_execute\n    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:\n\nDetected at node 'sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits' defined at (most recent call last):\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/runpy.py\", line 86, in _run_code\n      exec(code, run_globals)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel_launcher.py\", line 17, in <module>\n      app.launch_new_instance()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/traitlets/config/application.py\", line 992, in launch_instance\n      app.start()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 736, in start\n      self.io_loop.start()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 195, in start\n      self.asyncio_loop.run_forever()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n      self._run_once()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n      handle._run()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/asyncio/events.py\", line 80, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 516, in dispatch_queue\n      await self.process_one()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 505, in process_one\n      await dispatch(*args)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 412, in dispatch_shell\n      await result\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 740, in execute_request\n      reply_content = await reply_content\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n      res = shell.run_cell(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 546, in run_cell\n      return super().run_cell(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3024, in run_cell\n      result = self._run_cell(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3079, in _run_cell\n      result = runner(coro)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n      coro.send(None)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3284, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3466, in run_ast_nodes\n      if await self.run_code(code, result, async_=asy):\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3526, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"/var/folders/st/bgnz1xgs2hz0_cqmkbxt25r00000gn/T/ipykernel_12014/150609288.py\", line 1, in <module>\n      grid_search.fit(X,y)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/base.py\", line 1151, in wrapper\n      return fit_method(estimator, *args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_search.py\", line 898, in fit\n      self._run_search(evaluate_candidates)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_search.py\", line 1419, in _run_search\n      evaluate_candidates(ParameterGrid(self.param_grid))\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_search.py\", line 845, in evaluate_candidates\n      out = parallel(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n      return super().__call__(iterable_with_config)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 1088, in __call__\n      while self.dispatch_one_batch(iterator):\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 901, in dispatch_one_batch\n      self._dispatch(tasks)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 819, in _dispatch\n      job = self._backend.apply_async(batch, callback=cb)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/_parallel_backends.py\", line 208, in apply_async\n      result = ImmediateResult(func)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/_parallel_backends.py\", line 597, in __init__\n      self.results = batch()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 288, in __call__\n      return [func(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 288, in <listcomp>\n      return [func(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n      return self.function(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 732, in _fit_and_score\n      estimator.fit(X_train, y_train, **fit_params)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1491, in fit\n      super().fit(X=X, y=y, sample_weight=sample_weight, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 760, in fit\n      self._fit(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 928, in _fit\n      self._fit_keras_model(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 524, in _fit_keras_model\n      hist = self.model_.fit(x=X, y=y, **fit_args)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1650, in fit\n      tmp_logs = self.train_function(iterator)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1249, in train_function\n      return step_function(self, iterator)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1233, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1222, in run_step\n      outputs = model.train_step(data)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1024, in train_step\n      loss = self.compute_loss(x, y, y_pred, sample_weight)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1082, in compute_loss\n      return self.compiled_loss(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/compile_utils.py\", line 265, in __call__\n      loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/losses.py\", line 152, in __call__\n      losses = call_fn(y_true, y_pred)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/losses.py\", line 284, in call\n      return ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/losses.py\", line 2098, in sparse_categorical_crossentropy\n      return backend.sparse_categorical_crossentropy(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/backend.py\", line 5633, in sparse_categorical_crossentropy\n      res = tf.nn.sparse_softmax_cross_entropy_with_logits(\nNode: 'sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits'\nReceived a label value of 4 which is outside the valid range of [0, 1).  Label values: 3 3 3 3 3 3 3 3 3 3 0 3 3 3 3 2 0 3 2 4 3 0 3 1 0 3 3 3 1 3 2 3\n\t [[{{node sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits}}]] [Op:__inference_train_function_10025]\n\n--------------------------------------------------------------------------------\n1 fits failed with the following error:\nTraceback (most recent call last):\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 732, in _fit_and_score\n    estimator.fit(X_train, y_train, **fit_params)\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1491, in fit\n    super().fit(X=X, y=y, sample_weight=sample_weight, **kwargs)\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 760, in fit\n    self._fit(\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 928, in _fit\n    self._fit_keras_model(\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 524, in _fit_keras_model\n    hist = self.model_.fit(x=X, y=y, **fit_args)\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/utils/traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/tensorflow/python/eager/execute.py\", line 52, in quick_execute\n    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:\n\nDetected at node 'sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits' defined at (most recent call last):\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n      return _run_code(code, main_globals, None,\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/runpy.py\", line 86, in _run_code\n      exec(code, run_globals)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel_launcher.py\", line 17, in <module>\n      app.launch_new_instance()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/traitlets/config/application.py\", line 992, in launch_instance\n      app.start()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 736, in start\n      self.io_loop.start()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 195, in start\n      self.asyncio_loop.run_forever()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n      self._run_once()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n      handle._run()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/asyncio/events.py\", line 80, in _run\n      self._context.run(self._callback, *self._args)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 516, in dispatch_queue\n      await self.process_one()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 505, in process_one\n      await dispatch(*args)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 412, in dispatch_shell\n      await result\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 740, in execute_request\n      reply_content = await reply_content\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n      res = shell.run_cell(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 546, in run_cell\n      return super().run_cell(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3024, in run_cell\n      result = self._run_cell(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3079, in _run_cell\n      result = runner(coro)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n      coro.send(None)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3284, in run_cell_async\n      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3466, in run_ast_nodes\n      if await self.run_code(code, result, async_=asy):\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3526, in run_code\n      exec(code_obj, self.user_global_ns, self.user_ns)\n    File \"/var/folders/st/bgnz1xgs2hz0_cqmkbxt25r00000gn/T/ipykernel_12014/150609288.py\", line 1, in <module>\n      grid_search.fit(X,y)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/base.py\", line 1151, in wrapper\n      return fit_method(estimator, *args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_search.py\", line 898, in fit\n      self._run_search(evaluate_candidates)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_search.py\", line 1419, in _run_search\n      evaluate_candidates(ParameterGrid(self.param_grid))\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_search.py\", line 845, in evaluate_candidates\n      out = parallel(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 65, in __call__\n      return super().__call__(iterable_with_config)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 1088, in __call__\n      while self.dispatch_one_batch(iterator):\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 901, in dispatch_one_batch\n      self._dispatch(tasks)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 819, in _dispatch\n      job = self._backend.apply_async(batch, callback=cb)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/_parallel_backends.py\", line 208, in apply_async\n      result = ImmediateResult(func)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/_parallel_backends.py\", line 597, in __init__\n      self.results = batch()\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 288, in __call__\n      return [func(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/joblib/parallel.py\", line 288, in <listcomp>\n      return [func(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/utils/parallel.py\", line 127, in __call__\n      return self.function(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/sklearn/model_selection/_validation.py\", line 732, in _fit_and_score\n      estimator.fit(X_train, y_train, **fit_params)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 1491, in fit\n      super().fit(X=X, y=y, sample_weight=sample_weight, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 760, in fit\n      self._fit(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 928, in _fit\n      self._fit_keras_model(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/scikeras/wrappers.py\", line 524, in _fit_keras_model\n      hist = self.model_.fit(x=X, y=y, **fit_args)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/utils/traceback_utils.py\", line 65, in error_handler\n      return fn(*args, **kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1650, in fit\n      tmp_logs = self.train_function(iterator)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1249, in train_function\n      return step_function(self, iterator)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1233, in step_function\n      outputs = model.distribute_strategy.run(run_step, args=(data,))\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1222, in run_step\n      outputs = model.train_step(data)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1024, in train_step\n      loss = self.compute_loss(x, y, y_pred, sample_weight)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/training.py\", line 1082, in compute_loss\n      return self.compiled_loss(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/engine/compile_utils.py\", line 265, in __call__\n      loss_value = loss_obj(y_t, y_p, sample_weight=sw)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/losses.py\", line 152, in __call__\n      losses = call_fn(y_true, y_pred)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/losses.py\", line 284, in call\n      return ag_fn(y_true, y_pred, **self._fn_kwargs)\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/losses.py\", line 2098, in sparse_categorical_crossentropy\n      return backend.sparse_categorical_crossentropy(\n    File \"/Users/goncalobraga/miniconda3/envs/DAA/lib/python3.10/site-packages/keras/backend.py\", line 5633, in sparse_categorical_crossentropy\n      res = tf.nn.sparse_softmax_cross_entropy_with_logits(\nNode: 'sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits'\nReceived a label value of 4 which is outside the valid range of [0, 1).  Label values: 3 3 0 1 2 3 3 3 3 4 3 3 3 3 4 3 2 3 3 3 3 3 2 3 2 3 3 4 3 3 2 1\n\t [[{{node sparse_categorical_crossentropy/SparseSoftmaxCrossEntropyWithLogits/SparseSoftmaxCrossEntropyWithLogits}}]] [Op:__inference_train_function_11026]\n"
     ]
    }
   ],
   "source": [
    "grid_search.fit(X,y)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mRunning cells with 'base' requires the ipykernel package.\n",
      "\u001b[1;31mRun the following command to install 'ipykernel' into the Python environment. \n",
      "\u001b[1;31mCommand: 'conda install -n base ipykernel --update-deps --force-reinstall'"
     ]
    }
   ],
   "source": [
    "best_mlp_model = grid_search.best_estimator_\n",
    "print(best_mlp_model)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mRunning cells with 'base' requires the ipykernel package.\n",
      "\u001b[1;31mRun the following command to install 'ipykernel' into the Python environment. \n",
      "\u001b[1;31mCommand: 'conda install -n base ipykernel --update-deps --force-reinstall'"
     ]
    }
   ],
   "source": [
    "best_mlp_model.fit(X,y,epochs = 20, validation_data = (X,y), verbose = 1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mRunning cells with 'base' requires the ipykernel package.\n",
      "\u001b[1;31mRun the following command to install 'ipykernel' into the Python environment. \n",
      "\u001b[1;31mCommand: 'conda install -n base ipykernel --update-deps --force-reinstall'"
     ]
    }
   ],
   "source": [
    "predictions = best_mlp_model.predict(df_test)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mRunning cells with 'base' requires the ipykernel package.\n",
      "\u001b[1;31mRun the following command to install 'ipykernel' into the Python environment. \n",
      "\u001b[1;31mCommand: 'conda install -n base ipykernel --update-deps --force-reinstall'"
     ]
    }
   ],
   "source": [
    "df_predicoes = pd.DataFrame({'Result': predictions})\n",
    "df_predicoes['RowId'] = range(1, len(predictions) + 1)\n",
    "df_predicoes = df_predicoes[['RowId', 'Result']]\n",
    "\n",
    "df_predicoes.to_csv('../../../datasets/parte2/teste/neuralNetwork.csv', index=False)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "daa310",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
